### ISSUE TITLE
Question. The proper way to rebuild 'tools'

### ISSUE THREAD

**Issue by sviterok** [BeeswaxIO/beeswax-api#23]
Hi Beeswax Team,

What is the proper way of re-building testing tools from `./beeswax/tools/` (e.g. `augmentor_requests_generator` and `win_log_requester`)?

I've noticed that the tools were built using Bazel, but I couldn't find the `BUILD` file for it in this repo.

I'd like to extend them with the ability to generate Protobuf messages from human-readable JSON definitions.
_It's already implemented in my local fork, but I figured that it might be useful to commit it back. This change also requires a slightly newer version of Protobuf (due to one bug in the currently used version)_

Thanks!

**Comment by mike-beeswax** [comment]
Hi Roman,

There's nothing to build for the requestor tools--the tools in repo can be
run directly. We have been avoiding putting our BUILD files in that repo
and instead pre-building and uploading to the repo (which we realize is not
a standard practice).

One small request: the beeswax-api repo is lightly monitored for questions,
so if you have additional questions and you don't get a response in a few
days on the repo message board, please feel free to shoot a note to
support@beeswax.com.

Thank you!
Mike

Mike Munley
Director of Customer Success
Mike@beeswax.com

On Thu, Jan 25, 2018 at 7:40 PM, Roman Nekhoroshev <notifications@github.com

**Comment by sviterok** [comment]
Thanks, Mike!
That's what I figured. Alright, I'll keep my fork with JSON->Protobuf conversion locally then.
